name: Build and Push Docker Images

on:
  push:
    tags:
      - 'wp-*.*.*-php-*.*'  # Matches tags like wp-6.4.3-php-8.3
  workflow_dispatch:     # Allows manual trigger

env:
  REGISTRY: docker.io
  IMAGE_NAME: salsadigitalau/wordpress-lagoon-cli

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract versions from tag
        id: get-versions
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/wp-([0-9]+\.[0-9]+\.[0-9]+)-php-([0-9]+\.[0-9]+)$ ]]; then
            echo "WP_VERSION=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "PHP_VERSION=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
          else
            echo "WP_VERSION=6.4.3" >> $GITHUB_OUTPUT
            echo "PHP_VERSION=8.3" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push CLI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile.cli
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          build-args: |
            PHP_VERSION=${{ steps.get-versions.outputs.PHP_VERSION }}
            WP_VERSION=${{ steps.get-versions.outputs.WP_VERSION }}